import { Order, Clinic, CreditUsage } from '@/types';

export const mockClinics: Clinic[] = [
  {
    id: 'c1',
    name: 'Riverside Medical Center',
    location: 'Downtown',
    contactPerson: 'Dr. Sarah Johnson',
    contactEmail: 'sarah.j@riverside.med',
  },
  {
    id: 'c2',
    name: 'Oakwood Family Clinic',
    location: 'Westside',
    contactPerson: 'Dr. Michael Chen',
    contactEmail: 'mchen@oakwood.clinic',
  },
  {
    id: 'c3',
    name: 'Greenfield Health Center',
    location: 'North District',
    contactPerson: 'Dr. Emily Rodriguez',
    contactEmail: 'emily.r@greenfield.health',
  },
  {
    id: 'c4',
    name: 'Summit Wellness Clinic',
    location: 'East End',
    contactPerson: 'Dr. James Wilson',
    contactEmail: 'jwilson@summit.wellness',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'ORD-2024-001',
    clinicId: 'c1',
    clinicName: 'Riverside Medical Center',
    date: new Date('2024-01-15'),
    status: 'completed',
    itemsCount: 45,
    totalAmount: 3250.00,
    credits: 65,
  },
  {
    id: 'o2',
    orderNumber: 'ORD-2024-002',
    clinicId: 'c2',
    clinicName: 'Oakwood Family Clinic',
    date: new Date('2024-01-18'),
    status: 'processing',
    itemsCount: 32,
    totalAmount: 2180.00,
    credits: 44,
  },
  {
    id: 'o3',
    orderNumber: 'ORD-2024-003',
    clinicId: 'c1',
    clinicName: 'Riverside Medical Center',
    date: new Date('2024-01-20'),
    status: 'completed',
    itemsCount: 28,
    totalAmount: 1890.00,
    credits: 38,
  },
  {
    id: 'o4',
    orderNumber: 'ORD-2024-004',
    clinicId: 'c3',
    clinicName: 'Greenfield Health Center',
    date: new Date('2024-01-22'),
    status: 'pending',
    itemsCount: 52,
    totalAmount: 4120.00,
    credits: 82,
  },
  {
    id: 'o5',
    orderNumber: 'ORD-2024-005',
    clinicId: 'c4',
    clinicName: 'Summit Wellness Clinic',
    date: new Date('2024-01-25'),
    status: 'completed',
    itemsCount: 38,
    totalAmount: 2650.00,
    credits: 53,
  },
  {
    id: 'o6',
    orderNumber: 'ORD-2024-006',
    clinicId: 'c2',
    clinicName: 'Oakwood Family Clinic',
    date: new Date('2024-01-27'),
    status: 'processing',
    itemsCount: 41,
    totalAmount: 2980.00,
    credits: 60,
  },
  {
    id: 'o7',
    orderNumber: 'ORD-2024-007',
    clinicId: 'c3',
    clinicName: 'Greenfield Health Center',
    date: new Date('2024-01-28'),
    status: 'cancelled',
    itemsCount: 15,
    totalAmount: 950.00,
    credits: 19,
  },
];

export const mockCreditUsage: CreditUsage[] = [
  {
    clinicId: 'c1',
    clinicName: 'Riverside Medical Center',
    creditsUsed: 103,
    totalOrders: 2,
    lastOrderDate: new Date('2024-01-20'),
    amountBilled: 5140.00,
  },
  {
    clinicId: 'c2',
    clinicName: 'Oakwood Family Clinic',
    creditsUsed: 104,
    totalOrders: 2,
    lastOrderDate: new Date('2024-01-27'),
    amountBilled: 5160.00,
  },
  {
    clinicId: 'c3',
    clinicName: 'Greenfield Health Center',
    creditsUsed: 101,
    totalOrders: 2,
    lastOrderDate: new Date('2024-01-28'),
    amountBilled: 5070.00,
  },
  {
    clinicId: 'c4',
    clinicName: 'Summit Wellness Clinic',
    creditsUsed: 53,
    totalOrders: 1,
    lastOrderDate: new Date('2024-01-25'),
    amountBilled: 2650.00,
  },
];
